version: '3.7'

services:
  api:
    container_name: vrscraper_api
    build: .
    ports:
    - ${VRSCRAPER_APIPORT}:5000
    environment:
      VRSCRAPER_APIPORT: "${VRSCRAPER_APIPORT}"
    networks:
      - vr

networks:
  vr:
    name: custom_vr